apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-svc
spec:
  selector:
    matchLabels:
      app: webapp-svc
  template:
    metadata:
      labels:
        app: webapp-svc
    spec:
      containers:
      - name: webapp-svc
        image: lanchinho/web-app
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: webapp-svc-config
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: NEXTAUTH_SECRET
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp-svc
  ports:
  - port: 3000
    targetPort: 3000  